# serverless.yml

service: serverless-flask

plugins:
  - serverless-python-requirements
  - serverless-wsgi
custom:
  wsgi:
    app: app.app
    packRequirements: false
  s3Bucket: multiple-screens

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-west-2

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

resources:
  Resources:
    WebAppS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: multiple-screens
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html